### ISSUE TITLE
Add support for GTK.GLArea

### ISSUE THREAD

**Issue by bushyice** [node-3d/node-3d#7]
glfw is great, but it would be nice node-3d had an easy option to select another Gl while everything else works the same. 

I'm unsure, but currently i don't think there's an easy way to integrate node-3d into a node-gtk app, and i want to integrate it somehow.

I want to use the [Gtk.GLArea](https://docs.gtk.org/gtk4/class.GLArea.html) widget to render stuff like 3d, inside of a gtk app.

Is this a feature that could be added? or are there any other workarounds for it?

**Comment by raub** [comment]
Can you explain the app entry point design a bit more? For example:

- do you compile a GTK-based executable that uses V8 or Node for scripting, and then does the JS-GL scripting with help of `webgl-raub` - so that you launch YOUR.EXE?
- or are you going to make a GTK-based node addon that replaces the GLFW addon (and probably contains the rest of the app) - so that you launch NODE.EXE?

The initial options I can imagine:

- Substitute `glfw-raub` in `3d-core-raub` init call. But that doesn't sound reasonable, because you would need to mimic the whole interface.
- Don't use whole `3d-core-raub` and only use `webgl-raub` as it directly maps to GL calls and has no window/context related functionality/assumptions.
- Use `3d-core-raub` to render to texture, and share context with GTK in order to render the RTT'ed picture to your widget.
- The opposite of the former - render your GTK stuff to texture and send it back to `3d-core-raub`.


The last 2 cases involve some GL context magic that you probably won't appreciate, but I have a literal example of it working [HERE](https://github.com/node-3d/3d-qml-raub).

**Comment by bushyice** [comment]
No compilations needed, using node bindings api, node-gtk provides a way to use Gtk directly inside of the js. like this:
```coffee
gi = require 'node-gtk'

Gtk = gi.require 'gtk', '4.0'

app = new Gtk.Application 'com.something', false

app.on 'activate', () ->
  win = new Gtk.ApplicationWindow app;
  win.setDefaultSize 400, 300

  glArea = new Gtk.GLArea();


  glArea.on 'realize', =>
     gl = glArea.getContext()
     # do something with the context
  
  win.setChild glArea
  win.show()

app.run []
```

This is how you would normally run `node-gtk`, but the thing is, i want to use the `3d-raub-core` or the `webgl-raub` somehow.

```coffee
{ init, addThreeHelpers } = require '3d-core-raub';

ctx = init(
    gl: glArea.getContext()
    events: {
      resize: (cb) -> glArea.on 'resize', cb
   }
)
addThreeHelpers(Three, ctx.gl);
```
I am thinking that this could use the glArea's context and instead of opening a new window it uses this one, and for the events such as tapping/dragging/resizing i think the GLArea widget in Gtk has signals to handle that.

**Comment by raub** [comment]
Do you want to use three.js or some other libraries that assume you are in a browser? This is what is handled by packages `3d-core-raub` and `glfw-raub`. If you don't need that - you don't need those, it will be much easier.

Have you tried simply using `webgl-raub` right after `app.run []`? Does it work for `glArea`?

**Comment by bushyice** [comment]
Sorry for the late reply, i am not quite sure yet if glArea's context is compatible- but i'm currently trying out `glfw-raub`

**Comment by raub** [comment]
Any authentic OpenGL(/ES) context is compatible with `webgl-raub`. Meaning if GTK uses ANGLE (DirectX) - that won't be compatible after all. But I hope they don't.

**Comment by bushyice** [comment]
Yep, i think they do provide a OpenGL context. I will update you when i get the context and try to connect it.

**Comment by raub** [comment]
Feel free to reopen if there is any update on this. For now, I'm closing the issue as non-actionable on my side.
